// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndkbrbacpzmpvvyocmfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ka2JyYmFjcHptcHZ2eW9jbWZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMTE2MzYsImV4cCI6MjA3MTY4NzYzNn0.07Eu2uNoIrKx1RI7Kjt5gqWnRHhtDtCy1zN_T1t1S0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});